server:
  port: 8181
security:
  sessions: stateless
logging:
  level:
    root: WARN
    org.springframework.context.annotation.ConfigurationClassPostProcessor: ERROR
spring:
  jackson:
    default-property-inclusion: non_null
